unstable_features = true

# Imports.
imports_granularity = "Module"
group_imports = "StdExternalCrate"

# Comments.
wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
